name: Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: |
        cd wasm/
        wasm-pack build --target web --out-dir ../app/public/pkg/
    - run: |
        rm app/public/pkg/.gitignore
        rm app/public/pkg/*.ts
        rm app/public/pkg/*.json
    - run: |
        cd app/
        npm install
        npm run build
    - run: |
        cd build/
        echo "beta.eukolia.design" > CNAME
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/
