name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Build Rust
      run: |
        cd wasm
        cargo build --verbose
    - name: Run Rust tests
      run: |
        cd wasm
        cargo test --verbose
    - name: Build Wasm
      run: |
        cd wasm
        wasm-pack build --dev --target web --out-dir ../app/src/wasm/
    - name: Build Node
      run: |
        cd app
        npm ci
        npm run build --if-present
    - name: Run Node tests
      run: |
        cd app
        npm ci
        npm test
