name: Deploy

on:
  workflow_run:
    workflows: ["Rust", "Node.js"]
    branches: [main]
    types: 
      - completed
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Download wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build Wasm
      run: |
        cd wasm
        wasm-pack build --target web --out-dir ../app/public/pkg/
    - name: Clean files
      run: |
        rm app/public/pkg/.gitignore
        rm app/public/pkg/*.ts
        rm app/public/pkg/*.json
    - name: Build JS
      run: |
        cd app
        npm install
        npm run build
    - name: Create CNAME
      run: |
        cd build/
        echo "fluss.cedeber.fr" > CNAME
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/
