name: deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: npm install --global terser
    - run: |
        cd wasm/
        wasm-pack build --target web --out-dir ../app/public/pkg/
    - run: terser app/public/pkg/fluss.js --output app/public/pkg/fluss.min.js --compress --module --ecma 7
    - run: |
        rm app/public/pkg/.gitignore
        rm app/public/pkg/*.ts
        rm app/public/pkg/*.json
        rm app/public/pkg/fluss.js
        mv app/public/pkg/fluss.min.js app/public/pkg/fluss.js
    - run: npm install
    - run: npm run build
    - run: |
        cd build/
        echo "beta.eukolia.design" > CNAME
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/
