name: Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Build
      run: |
        cd app
        npm ci
        npm run build --if-present
    - name: Run tests
      run: |
        cd app
        npm ci
        npm test
